Added a run() function
FRC1076/2018-Competition pull request #17
Opened 2018-02-03 01:25 UTC by WilliamBallbach

Adds a ```run()``` function to probably be useful eventually

2018-02-03 01:50 UTC, porglezomp requested changes

2018-02-03 01:50 UTC, porglezomp commented on autonomous.py
> +        self.init()
we should put in a nested function that does everything in execute then ends, like
```python
def _execute():
    yield from self.execute()
    self.end()
```
then we can `return _execute()` instead

2018-02-03 01:50 UTC, porglezomp commented on autonomous.py
>  class Timed:
The `end()` for `Timed` should call the inner `end()`.

2018-02-03 01:50 UTC, porglezomp commented on robot.py
>              # WPILib prints a ton of error messages when the motor has no output
We should call `self.auton.end()` here

2018-02-03 02:00 UTC, WilliamBallbach commented
I changed things, but I don't know if I did it right

2018-02-03 18:53 UTC, porglezomp commented
Looks like those changes don't work. Remember to run tests (`python3 robot.py test` (or on Windows,`py -3 robot.py test`) so you can find out if the code works.

2018-02-04 21:08 UTC, WilliamBallbach commented
It passes the tests now, but I'm not sure how to implement your second and third suggestions

2018-02-16 22:52 UTC, a2aaron approved these changes
This appears to have all the changes done!

2018-02-16 23:42 UTC, porglezomp approved these changes
Okay, looks good

2018-02-16 23:42 UTC, merged