elevator subsystem
FRC1076/2018-Competition pull request #4
Opened 2018-01-13 21:42 UTC by helenaheinonen

wrote elevator code: moves grabber up and down to reach cubes

2018-01-13 21:47 UTC, Hannah3333 approved these changes
LAAGASTM

2018-01-14 01:29 UTC, porglezomp requested changes
This looks good, but we should get some tests on this. Merge from develop into your branch, and write a test in the tests folder to make sure these do what we expect.

2018-01-14 23:26 UTC, porglezomp approved these changes
This looks good! 😺

2018-01-14 23:26 UTC, porglezomp commented on tests/elevator_test.py
> +
nice separation

2018-01-14 23:27 UTC, merged