Subsystem/grabber
FRC1076/2018-Competition pull request #5
Opened 2018-01-13 21:44 UTC by Hannah3333

Wrote code for the grabber--absorbing the cube, sensing once the cube has been absorbed, and spitting out the cube.

2018-01-13 21:48 UTC, porglezomp requested changes
Needs different whitespace

2018-01-13 21:48 UTC, porglezomp commented on subsystems/grabber.py
> +		The grabber will absorb a cube,
The docstring shouldn't be indented like this

2018-01-13 21:49 UTC, helenaheinonen approved these changes
looks like my cat which means its good✨ 🐱

2018-01-13 21:55 UTC, PCain21 approved these changes
looks good

2018-01-13 21:56 UTC, porglezomp approved these changes
LGTM

2018-01-14 01:28 UTC, porglezomp requested changes
Actually, let's get some tests on this. Merge from `develop` into your branch, and write a test in the `tests` folder to make sure these do what we expect.

2018-01-14 23:30 UTC, porglezomp approved these changes
You could format it nicer in the future, but this is good.

2018-01-14 23:30 UTC, porglezomp commented on tests/grabber_test.py
> +
In the future keep the end clean, not so many blank lines

2018-01-14 23:30 UTC, porglezomp commented on tests/grabber_test.py
> +    assert not grabber.has_cube()
In the future, it's nice to separate the different sections with extra space, like
```python
grabber.absorb(speed=0.5)
assert left_motor.state == 0.5
assert right_motor.state == -0.5

grabber.spit()
assert left_motor.state == -1
assert right_motor.state == 1
```

2018-01-14 23:30 UTC, merged